In [2]:
import nibabel as nib
from pathlib import Path

print(nib.__version__)

5.4.2


In [4]:
nifti_path = Path(
    "../data/raw/nifti_test_studies/sub-001_ses-01_T1w.nii.gz"
    )

img = nib.load(nifti_path)

In [6]:
print(type(img))
header = img.header

print(header)

<class 'nibabel.nifti1.Nifti1Image'>
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 54
dim             : [  3 192 256 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.     0.9    0.9375 0.9375 2.3    0.     0.     0.    ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'TE=2.3;Time=133419.890;phase=1'
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : -1.490115053570662e-08
quatern_c       : -1.5050200090627186e-06
quat

In [11]:
print(img.shape)
print(header.get_zooms())
print(header.get_data_dtype())

(192, 256, 256)
(np.float32(0.9), np.float32(0.9375), np.float32(0.9375))
int16


In [13]:
data = img.get_fdata()

print(type(data))
print(data.shape)
print(data.dtype)

print(img.affine)

<class 'numpy.ndarray'>
(192, 256, 256)
float64
[[ 8.99999976e-01  1.87196247e-06 -2.82191240e-06 -8.59498520e+01]
 [-1.79708388e-06  9.37500000e-01  2.79424679e-08 -1.19062157e+02]
 [ 2.70903593e-06 -2.79368439e-08  9.37500000e-01 -1.19063019e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [15]:
print("Tipo:", type(img))
print("Shape:", img.shape)
print("Header:", type(img.header))
print("Voxel size:", img.header.get_zooms())
print("Datatype:", img.header.get_data_dtype())
print("Affine:")
print(img.affine)

print("Data type:", type(data))
print("Data shape:", data.shape)
print("Data dtype:", data.dtype)

Tipo: <class 'nibabel.nifti1.Nifti1Image'>
Shape: (192, 256, 256)
Header: <class 'nibabel.nifti1.Nifti1Header'>
Voxel size: (np.float32(0.9), np.float32(0.9375), np.float32(0.9375))
Datatype: int16
Affine:
[[ 8.99999976e-01  1.87196247e-06 -2.82191240e-06 -8.59498520e+01]
 [-1.79708388e-06  9.37500000e-01  2.79424679e-08 -1.19062157e+02]
 [ 2.70903593e-06 -2.79368439e-08  9.37500000e-01 -1.19063019e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Data type: <class 'numpy.ndarray'>
Data shape: (192, 256, 256)
Data dtype: float64


In [18]:
print("qform:")
print(img.header.get_qform())

print("\nsform:")
print(img.header.get_sform())

print("\nqform_code:", img.header["qform_code"])
print("sform_code:", img.header["sform_code"])

qform:
[[ 8.99999976e-01  1.87196247e-06 -2.82191249e-06 -8.59498520e+01]
 [-1.79708384e-06  9.37500000e-01  2.79424746e-08 -1.19062157e+02]
 [ 2.70903597e-06 -2.79368399e-08  9.37500000e-01 -1.19063019e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

sform:
[[ 8.99999976e-01  1.87196247e-06 -2.82191240e-06 -8.59498520e+01]
 [-1.79708388e-06  9.37500000e-01  2.79424679e-08 -1.19062157e+02]
 [ 2.70903593e-06 -2.79368439e-08  9.37500000e-01 -1.19063019e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

qform_code: 1
sform_code: 1


In [19]:
for field in [
    "dim",
    "pixdim",
    "datatype",
    "bitpix",
    "scl_slope",
    "scl_inter",
]:
    print(field, "=", img.header[field])

dim = [  3 192 256 256   1   1   1   1]
pixdim = [1.     0.9    0.9375 0.9375 2.3    0.     0.     0.    ]
datatype = 4
bitpix = 16
scl_slope = nan
scl_inter = nan


In [20]:
print("Min:", data.min())
print("Max:", data.max())
print("Mean:", data.mean())

Min: 0.0
Max: 1100.0000607781112
Mean: 94.6445539671917


In [22]:
print(nib.aff2axcodes(img.affine))
print(nib.orientations.io_orientation(img.affine))

('R', 'A', 'S')
[[0. 1.]
 [1. 1.]
 [2. 1.]]
